config/routes.rb
Rails.application.routes.draw do

	resources :orders do
		member do
			get :pay_with_credit_card
			post :pay2go_cc_notify
		end
	end

	root "products#index"	

	resources :items, controller: "cart_items"

	namespace :account do
		resources :orders
	end

	resources :carts do
		collection do
			post :checkout
			delete :clean
		end
	end

	devise_for :users

	namespace :admin do
		resources :products

		resources :orders do
			member do
				post :cancel
				post :ship
				post :shipped
				post :return
			end
		end

		resources :users do
			member do
				post :to_admin
				post :to_normal
			end
		end
	end

	resources :products do
		member do
			post :add_to_cart
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :photo

	accepts_nested_attributes_for :photo
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def edit
    @product = Product.find(params[:id])

    if @product.photo.present?
       @photo = @product.photo
     else
       @photo = @product.build_photo
     end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price,
                                    photo_attributes: [:image, :id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def add_to_cart
		@product = Product.find(params[:id])

		if !current_cart.items.include?(@product)
			current_cart.add_product_to_cart(@product)
			flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
		else
			flash[:warning] = "你的購物車內已有此物品"
		end

		redirect_to :back
	end

	helper_method :current_cart

	def current_cart
		@current_cart ||= find_cart
	end

	private

	def find_cart
		cart = Cart.find_by(id: session[:cart_id])

		unless cart.present?
			cart = Cart.create
		end

		session[:cart_id] = cart.id
		cart
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h2> 新增產品 </h2>

<%= simple_form_for [:admin, @product] do |f| %>

	<div class="group">
		<%= f.input :title %>
	</div>

	<div class="group">
		<%= f.input :description %>
	</div>

	<div class="group">
		<%= f.input :quantity %>
	</div>

	<div class="group">
		<%= f.input :price %>
	</div>

	<% if @photo.image.present? %>
		<span>目前商品圖</span> <br>
		<%= image_tag(@photo.image.thumb.url) %>
	<% end %>

	<div class="form-group">
		<%= f.simple_fields_for :photo do |c| %>
			<%= c.input :image , as: :file %>
		<% end %>
	</div>

	<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
	<%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>#</th>
			<th width="220">Product Pic</th>
			<th>Name</th>
			<th>Price</th>
			<th width="100"> Options</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
			<tr>
				<td>
					<%= product.id %>
				</td>
				<td>
					<%= link_to product_path(product) do %>
						<% if product.photo.present? %>
							<%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
						<% else %>
							<%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
						<% end %>
					<% end %>
				</td>
				<td>
					<%= product.title %>
				</td>
				<td>
					<%= product.price %>
				</td>
				<td>
					<%= link_to("Edit", edit_admin_product_path(product)) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/products/new.html.erb
<h2> 新增產品 </h2>

<%= simple_form_for [:admin, @product] do |f| %>

	<div class="group">
		<%= f.input :title %>
	</div>

	<div class="group">
		<%= f.input :description %>
	</div>

	<div class="group">
		<%= f.input :quantity %>
	</div>

	<div class="group">
		<%= f.input :price %>
	</div>

	<div class="form-group">
		<%= f.simple_fields_for :photo do |c| %>
			<%= c.input :image , as: :file %>
		<% end %>
	</div>

	<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>