config/routes.rb
Rails.application.routes.draw do

	resources :orders do
		member do
			get :pay_with_credit_card
			post :pay2go_cc_notify
		end
	end

	root "products#index"	

	resources :items, controller: "cart_items"

	namespace :account do
		resources :orders
	end

	resources :carts do
		collection do
			post :checkout
			delete :clean
		end
	end

	devise_for :users

	namespace :admin do
		resources :products

		resources :orders do
			member do
				post :cancel
				post :ship
				post :shipped
				post :return
			end
		end

		resources :users do
			member do
				post :to_admin
				post :to_normal
			end
		end
	end

	resources :products do
		member do
			post :add_to_cart
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :photo

	accepts_nested_attributes_for :photo
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def edit
    @product = Product.find(params[:id])

    if @product.photo.present?
       @photo = @product.photo
     else
       @photo = @product.build_photo
     end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price,
                                    photo_attributes: [:image, :id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def add_to_cart
		@product = Product.find(params[:id])

		if !current_cart.items.include?(@product)
			current_cart.add_product_to_cart(@product)
			flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
		else
			flash[:warning] = "你的購物車內已有此物品"
		end

		redirect_to :back
	end

	helper_method :current_cart

	def current_cart
		@current_cart ||= find_cart
	end

	private

	def find_cart
		cart = Cart.find_by(id: session[:cart_id])

		unless cart.present?
			cart = Cart.create
		end

		session[:cart_id] = cart.id
		cart
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-xs-6 col-md-3">
			<%= link_to product_path(product) do %>
				<% if product.photo.present? %>
					<%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
				<% else %>
					<%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
				<% end %>
			<% end %>
			<%= product.title %> $ <%= product.price %>
		</div>
	<% end %>
</div>

app/views/products/show.html.erb
<div class="row">
	<div class="col-md-6">
		<% if @product.photo.present? %>
			<%= image_tag(@product.photo.image.medium.url, class: "thumbnail") %>
		<% else %>
			<%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
		<% end %>
	</div>
	<div class="col-md-6">
		<h2> <%= @product.title %> </h2>
		<div style="height:100px;">
			<p>
				<%= @product.description %>
			</p>
		</div>
		<div> 數量 : <%= @product.quantity %> </div>
		<div class="product-price"> $ <%= @product.price %> </div>
		<div class="pull-right">
			<% if @product.quantity > 0 %>
				<%= link_to("加入購物車", add_to_cart_product_path(@product), method: :post, class: "btn btn-lg btn-danger") %>
			<% else %>
				已銷售一空，無法購買
			<% end %>
		</div>
	</div>
</div>